version: "3.7"
volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/adidion/data/database
      type: volume
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/adidion/data/wordpress
      type: volume
      o: bind

networks:
  my-network:

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: img_nginx
    volumes:
      - "wordpress_volume:/var/www/wordpress/"
    networks:
      - my-network
    ports:
      - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: img_mariadb
    volumes:
      - "mariadb_volume:/var/lib/mysql"
    networks:
      - my-network
    environment:
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_DB=${MARIADB_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    image: img_wordpress
    volumes:
      - "wordpress_volume:/var/www/wordpress/"
    networks:
      - my-network
    environment:
      - WP_URL=${WP_URL}
      - WP_DATABASE=${WP_DATABASE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
      - MARIADB_DB=${MARIADB_DB}
    restart: always
